server:
  port: 8780

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/schedulercld_task?useSSL=false
    #?createDatabaseIfNotExist=true
    username: root
    password: MadLove@17
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      #ddl-auto: create